#!/bin/bash
set -e

docker build . --tag dog

docker rm -f dog || true
docker run --name dog -d -it --restart=unless-stopped dog

echo "###################################################"
echo "ctrl-c to stop, docker container will keep running:"
echo "To get rid of it, type: docker rm -f dog"
echo "###################################################"

docker logs -f dog
