#pragma once
#define TUNE_BISHOP_COUNT	0
#define TUNE_TOO_MANY_PAWNS	0
#define TUNE_ZERO_PAWNS	0
#define TUNE_ISOLATED_PAWNS	-0
#define TUNE_ROOK_ON_OPEN_FILE	0
#define TUNE_DOUBLE_PAWNS	0
#define TUNE_BISHOP_OPEN_DIAGONAL	0
#define TUNE_PAWN	0
#define TUNE_KNIGHT	0
#define TUNE_BISHOP	0
#define TUNE_ROOK	0
#define TUNE_QUEEN	0
#define TUNE_KING_SHIELD	0
#define TUNE_PSQ_MUL	0
#define TUNE_PSQ_DIV	1
#define TUNE_EDGE_BLACK_RANK	0
#define TUNE_EDGE_BLACK_FILE	0
#define TUNE_EDGE_WHITE_RANK	0
#define TUNE_EDGE_WHITE_FILE	0
#define TUNE_BIG_DELTA_PROMOTION	0
#define TUNE_BIG_DELTA	0
#define TUNE_PP_SCORES_MG_1	-0
#define TUNE_PP_SCORES_MG_2	-0
#define TUNE_PP_SCORES_MG_3	0
#define TUNE_PP_SCORES_MG_4	0
#define TUNE_PP_SCORES_MG_5	0
#define TUNE_PP_SCORES_MG_6	0
#define TUNE_PP_SCORES_EG_1	0
#define TUNE_PP_SCORES_EG_2	-0
#define TUNE_PP_SCORES_EG_3	-0
#define TUNE_PP_SCORES_EG_4	0
#define TUNE_PP_SCORES_EG_5	0
#define TUNE_PP_SCORES_EG_6	0
#define TUNE_PP_SCORES_EG_0 0
#define TUNE_PP_SCORES_EG_7 0
#define TUNE_PP_SCORES_MG_0 0
#define TUNE_PP_SCORES_MG_7 0
#define PawnPSTMG_A1 0
#define PawnPSTMG_B1 0
#define PawnPSTMG_C1 0
#define PawnPSTMG_D1 0
#define PawnPSTMG_E1 0
#define PawnPSTMG_F1 0
#define PawnPSTMG_G1 0
#define PawnPSTMG_H1 0
#define PawnPSTMG_A2 0
#define PawnPSTMG_B2 0
#define PawnPSTMG_C2 0
#define PawnPSTMG_D2 0
#define PawnPSTMG_E2 0
#define PawnPSTMG_F2 0
#define PawnPSTMG_G2 0
#define PawnPSTMG_H2 0
#define PawnPSTMG_A3 0
#define PawnPSTMG_B3 0
#define PawnPSTMG_C3 0
#define PawnPSTMG_D3 0
#define PawnPSTMG_E3 0
#define PawnPSTMG_F3 0
#define PawnPSTMG_G3 0
#define PawnPSTMG_H3 0
#define PawnPSTMG_A4 0
#define PawnPSTMG_B4 0
#define PawnPSTMG_C4 0
#define PawnPSTMG_D4 0
#define PawnPSTMG_E4 0
#define PawnPSTMG_F4 0
#define PawnPSTMG_G4 0
#define PawnPSTMG_H4 0
#define PawnPSTMG_A5 0
#define PawnPSTMG_B5 0
#define PawnPSTMG_C5 0
#define PawnPSTMG_D5 0
#define PawnPSTMG_E5 0
#define PawnPSTMG_F5 0
#define PawnPSTMG_G5 0
#define PawnPSTMG_H5 0
#define PawnPSTMG_A6 0
#define PawnPSTMG_B6 0
#define PawnPSTMG_C6 0
#define PawnPSTMG_D6 0
#define PawnPSTMG_E6 0
#define PawnPSTMG_F6 0
#define PawnPSTMG_G6 0
#define PawnPSTMG_H6 0
#define PawnPSTMG_A7 0
#define PawnPSTMG_B7 0
#define PawnPSTMG_C7 0
#define PawnPSTMG_D7 0
#define PawnPSTMG_E7 0
#define PawnPSTMG_F7 0
#define PawnPSTMG_G7 0
#define PawnPSTMG_H7 0
#define PawnPSTMG_A8 0
#define PawnPSTMG_B8 0
#define PawnPSTMG_C8 0
#define PawnPSTMG_D8 0
#define PawnPSTMG_E8 0
#define PawnPSTMG_F8 0
#define PawnPSTMG_G8 0
#define PawnPSTMG_H8 0
#define PawnPSTEG_A1 0
#define PawnPSTEG_B1 0
#define PawnPSTEG_C1 0
#define PawnPSTEG_D1 0
#define PawnPSTEG_E1 0
#define PawnPSTEG_F1 0
#define PawnPSTEG_G1 0
#define PawnPSTEG_H1 0
#define PawnPSTEG_A2 0
#define PawnPSTEG_B2 0
#define PawnPSTEG_C2 0
#define PawnPSTEG_D2 0
#define PawnPSTEG_E2 0
#define PawnPSTEG_F2 0
#define PawnPSTEG_G2 0
#define PawnPSTEG_H2 0
#define PawnPSTEG_A3 0
#define PawnPSTEG_B3 0
#define PawnPSTEG_C3 0
#define PawnPSTEG_D3 0
#define PawnPSTEG_E3 0
#define PawnPSTEG_F3 0
#define PawnPSTEG_G3 0
#define PawnPSTEG_H3 0
#define PawnPSTEG_A4 0
#define PawnPSTEG_B4 0
#define PawnPSTEG_C4 0
#define PawnPSTEG_D4 0
#define PawnPSTEG_E4 0
#define PawnPSTEG_F4 0
#define PawnPSTEG_G4 0
#define PawnPSTEG_H4 0
#define PawnPSTEG_A5 0
#define PawnPSTEG_B5 0
#define PawnPSTEG_C5 0
#define PawnPSTEG_D5 0
#define PawnPSTEG_E5 0
#define PawnPSTEG_F5 0
#define PawnPSTEG_G5 0
#define PawnPSTEG_H5 0
#define PawnPSTEG_A6 0
#define PawnPSTEG_B6 0
#define PawnPSTEG_C6 0
#define PawnPSTEG_D6 0
#define PawnPSTEG_E6 0
#define PawnPSTEG_F6 0
#define PawnPSTEG_G6 0
#define PawnPSTEG_H6 0
#define PawnPSTEG_A7 0
#define PawnPSTEG_B7 0
#define PawnPSTEG_C7 0
#define PawnPSTEG_D7 0
#define PawnPSTEG_E7 0
#define PawnPSTEG_F7 0
#define PawnPSTEG_G7 0
#define PawnPSTEG_H7 0
#define PawnPSTEG_A8 0
#define PawnPSTEG_B8 0
#define PawnPSTEG_C8 0
#define PawnPSTEG_D8 0
#define PawnPSTEG_E8 0
#define PawnPSTEG_F8 0
#define PawnPSTEG_G8 0
#define PawnPSTEG_H8 0
#define KnightPSTMG_A1 0
#define KnightPSTMG_B1 0
#define KnightPSTMG_C1 0
#define KnightPSTMG_D1 0
#define KnightPSTMG_E1 0
#define KnightPSTMG_F1 0
#define KnightPSTMG_G1 0
#define KnightPSTMG_H1 0
#define KnightPSTMG_A2 0
#define KnightPSTMG_B2 0
#define KnightPSTMG_C2 0
#define KnightPSTMG_D2 0
#define KnightPSTMG_E2 0
#define KnightPSTMG_F2 0
#define KnightPSTMG_G2 0
#define KnightPSTMG_H2 0
#define KnightPSTMG_A3 0
#define KnightPSTMG_B3 0
#define KnightPSTMG_C3 0
#define KnightPSTMG_D3 0
#define KnightPSTMG_E3 0
#define KnightPSTMG_F3 0
#define KnightPSTMG_G3 0
#define KnightPSTMG_H3 0
#define KnightPSTMG_A4 0
#define KnightPSTMG_B4 0
#define KnightPSTMG_C4 0
#define KnightPSTMG_D4 0
#define KnightPSTMG_E4 0
#define KnightPSTMG_F4 0
#define KnightPSTMG_G4 0
#define KnightPSTMG_H4 0
#define KnightPSTMG_A5 0
#define KnightPSTMG_B5 0
#define KnightPSTMG_C5 0
#define KnightPSTMG_D5 0
#define KnightPSTMG_E5 0
#define KnightPSTMG_F5 0
#define KnightPSTMG_G5 0
#define KnightPSTMG_H5 0
#define KnightPSTMG_A6 0
#define KnightPSTMG_B6 0
#define KnightPSTMG_C6 0
#define KnightPSTMG_D6 0
#define KnightPSTMG_E6 0
#define KnightPSTMG_F6 0
#define KnightPSTMG_G6 0
#define KnightPSTMG_H6 0
#define KnightPSTMG_A7 0
#define KnightPSTMG_B7 0
#define KnightPSTMG_C7 0
#define KnightPSTMG_D7 0
#define KnightPSTMG_E7 0
#define KnightPSTMG_F7 0
#define KnightPSTMG_G7 0
#define KnightPSTMG_H7 0
#define KnightPSTMG_A8 0
#define KnightPSTMG_B8 0
#define KnightPSTMG_C8 0
#define KnightPSTMG_D8 0
#define KnightPSTMG_E8 0
#define KnightPSTMG_F8 0
#define KnightPSTMG_G8 0
#define KnightPSTMG_H8 0
#define KnightPSTEG_A1 0
#define KnightPSTEG_B1 0
#define KnightPSTEG_C1 0
#define KnightPSTEG_D1 0
#define KnightPSTEG_E1 0
#define KnightPSTEG_F1 0
#define KnightPSTEG_G1 0
#define KnightPSTEG_H1 0
#define KnightPSTEG_A2 0
#define KnightPSTEG_B2 0
#define KnightPSTEG_C2 0
#define KnightPSTEG_D2 0
#define KnightPSTEG_E2 0
#define KnightPSTEG_F2 0
#define KnightPSTEG_G2 0
#define KnightPSTEG_H2 0
#define KnightPSTEG_A3 0
#define KnightPSTEG_B3 0
#define KnightPSTEG_C3 0
#define KnightPSTEG_D3 0
#define KnightPSTEG_E3 0
#define KnightPSTEG_F3 0
#define KnightPSTEG_G3 0
#define KnightPSTEG_H3 0
#define KnightPSTEG_A4 0
#define KnightPSTEG_B4 0
#define KnightPSTEG_C4 0
#define KnightPSTEG_D4 0
#define KnightPSTEG_E4 0
#define KnightPSTEG_F4 0
#define KnightPSTEG_G4 0
#define KnightPSTEG_H4 0
#define KnightPSTEG_A5 0
#define KnightPSTEG_B5 0
#define KnightPSTEG_C5 0
#define KnightPSTEG_D5 0
#define KnightPSTEG_E5 0
#define KnightPSTEG_F5 0
#define KnightPSTEG_G5 0
#define KnightPSTEG_H5 0
#define KnightPSTEG_A6 0
#define KnightPSTEG_B6 0
#define KnightPSTEG_C6 0
#define KnightPSTEG_D6 0
#define KnightPSTEG_E6 0
#define KnightPSTEG_F6 0
#define KnightPSTEG_G6 0
#define KnightPSTEG_H6 0
#define KnightPSTEG_A7 0
#define KnightPSTEG_B7 0
#define KnightPSTEG_C7 0
#define KnightPSTEG_D7 0
#define KnightPSTEG_E7 0
#define KnightPSTEG_F7 0
#define KnightPSTEG_G7 0
#define KnightPSTEG_H7 0
#define KnightPSTEG_A8 0
#define KnightPSTEG_B8 0
#define KnightPSTEG_C8 0
#define KnightPSTEG_D8 0
#define KnightPSTEG_E8 0
#define KnightPSTEG_F8 0
#define KnightPSTEG_G8 0
#define KnightPSTEG_H8 0
#define BishopPSTMG_A1 0
#define BishopPSTMG_B1 0
#define BishopPSTMG_C1 0
#define BishopPSTMG_D1 0
#define BishopPSTMG_E1 0
#define BishopPSTMG_F1 0
#define BishopPSTMG_G1 0
#define BishopPSTMG_H1 0
#define BishopPSTMG_A2 0
#define BishopPSTMG_B2 0
#define BishopPSTMG_C2 0
#define BishopPSTMG_D2 0
#define BishopPSTMG_E2 0
#define BishopPSTMG_F2 0
#define BishopPSTMG_G2 0
#define BishopPSTMG_H2 0
#define BishopPSTMG_A3 0
#define BishopPSTMG_B3 0
#define BishopPSTMG_C3 0
#define BishopPSTMG_D3 0
#define BishopPSTMG_E3 0
#define BishopPSTMG_F3 0
#define BishopPSTMG_G3 0
#define BishopPSTMG_H3 0
#define BishopPSTMG_A4 0
#define BishopPSTMG_B4 0
#define BishopPSTMG_C4 0
#define BishopPSTMG_D4 0
#define BishopPSTMG_E4 0
#define BishopPSTMG_F4 0
#define BishopPSTMG_G4 0
#define BishopPSTMG_H4 0
#define BishopPSTMG_A5 0
#define BishopPSTMG_B5 0
#define BishopPSTMG_C5 0
#define BishopPSTMG_D5 0
#define BishopPSTMG_E5 0
#define BishopPSTMG_F5 0
#define BishopPSTMG_G5 0
#define BishopPSTMG_H5 0
#define BishopPSTMG_A6 0
#define BishopPSTMG_B6 0
#define BishopPSTMG_C6 0
#define BishopPSTMG_D6 0
#define BishopPSTMG_E6 0
#define BishopPSTMG_F6 0
#define BishopPSTMG_G6 0
#define BishopPSTMG_H6 0
#define BishopPSTMG_A7 0
#define BishopPSTMG_B7 0
#define BishopPSTMG_C7 0
#define BishopPSTMG_D7 0
#define BishopPSTMG_E7 0
#define BishopPSTMG_F7 0
#define BishopPSTMG_G7 0
#define BishopPSTMG_H7 0
#define BishopPSTMG_A8 0
#define BishopPSTMG_B8 0
#define BishopPSTMG_C8 0
#define BishopPSTMG_D8 0
#define BishopPSTMG_E8 0
#define BishopPSTMG_F8 0
#define BishopPSTMG_G8 0
#define BishopPSTMG_H8 0
#define BishopPSTEG_A1 0
#define BishopPSTEG_B1 0
#define BishopPSTEG_C1 0
#define BishopPSTEG_D1 0
#define BishopPSTEG_E1 0
#define BishopPSTEG_F1 0
#define BishopPSTEG_G1 0
#define BishopPSTEG_H1 0
#define BishopPSTEG_A2 0
#define BishopPSTEG_B2 0
#define BishopPSTEG_C2 0
#define BishopPSTEG_D2 0
#define BishopPSTEG_E2 0
#define BishopPSTEG_F2 0
#define BishopPSTEG_G2 0
#define BishopPSTEG_H2 0
#define BishopPSTEG_A3 0
#define BishopPSTEG_B3 0
#define BishopPSTEG_C3 0
#define BishopPSTEG_D3 0
#define BishopPSTEG_E3 0
#define BishopPSTEG_F3 0
#define BishopPSTEG_G3 0
#define BishopPSTEG_H3 0
#define BishopPSTEG_A4 0
#define BishopPSTEG_B4 0
#define BishopPSTEG_C4 0
#define BishopPSTEG_D4 0
#define BishopPSTEG_E4 0
#define BishopPSTEG_F4 0
#define BishopPSTEG_G4 0
#define BishopPSTEG_H4 0
#define BishopPSTEG_A5 0
#define BishopPSTEG_B5 0
#define BishopPSTEG_C5 0
#define BishopPSTEG_D5 0
#define BishopPSTEG_E5 0
#define BishopPSTEG_F5 0
#define BishopPSTEG_G5 0
#define BishopPSTEG_H5 0
#define BishopPSTEG_A6 0
#define BishopPSTEG_B6 0
#define BishopPSTEG_C6 0
#define BishopPSTEG_D6 0
#define BishopPSTEG_E6 0
#define BishopPSTEG_F6 0
#define BishopPSTEG_G6 0
#define BishopPSTEG_H6 0
#define BishopPSTEG_A7 0
#define BishopPSTEG_B7 0
#define BishopPSTEG_C7 0
#define BishopPSTEG_D7 0
#define BishopPSTEG_E7 0
#define BishopPSTEG_F7 0
#define BishopPSTEG_G7 0
#define BishopPSTEG_H7 0
#define BishopPSTEG_A8 0
#define BishopPSTEG_B8 0
#define BishopPSTEG_C8 0
#define BishopPSTEG_D8 0
#define BishopPSTEG_E8 0
#define BishopPSTEG_F8 0
#define BishopPSTEG_G8 0
#define BishopPSTEG_H8 0
#define RookPSTMG_A1 0
#define RookPSTMG_B1 0
#define RookPSTMG_C1 0
#define RookPSTMG_D1 0
#define RookPSTMG_E1 0
#define RookPSTMG_F1 0
#define RookPSTMG_G1 0
#define RookPSTMG_H1 0
#define RookPSTMG_A2 0
#define RookPSTMG_B2 0
#define RookPSTMG_C2 0
#define RookPSTMG_D2 0
#define RookPSTMG_E2 0
#define RookPSTMG_F2 0
#define RookPSTMG_G2 0
#define RookPSTMG_H2 0
#define RookPSTMG_A3 0
#define RookPSTMG_B3 0
#define RookPSTMG_C3 0
#define RookPSTMG_D3 0
#define RookPSTMG_E3 0
#define RookPSTMG_F3 0
#define RookPSTMG_G3 0
#define RookPSTMG_H3 0
#define RookPSTMG_A4 0
#define RookPSTMG_B4 0
#define RookPSTMG_C4 0
#define RookPSTMG_D4 0
#define RookPSTMG_E4 0
#define RookPSTMG_F4 0
#define RookPSTMG_G4 0
#define RookPSTMG_H4 0
#define RookPSTMG_A5 0
#define RookPSTMG_B5 0
#define RookPSTMG_C5 0
#define RookPSTMG_D5 0
#define RookPSTMG_E5 0
#define RookPSTMG_F5 0
#define RookPSTMG_G5 0
#define RookPSTMG_H5 0
#define RookPSTMG_A6 0
#define RookPSTMG_B6 0
#define RookPSTMG_C6 0
#define RookPSTMG_D6 0
#define RookPSTMG_E6 0
#define RookPSTMG_F6 0
#define RookPSTMG_G6 0
#define RookPSTMG_H6 0
#define RookPSTMG_A7 0
#define RookPSTMG_B7 0
#define RookPSTMG_C7 0
#define RookPSTMG_D7 0
#define RookPSTMG_E7 0
#define RookPSTMG_F7 0
#define RookPSTMG_G7 0
#define RookPSTMG_H7 0
#define RookPSTMG_A8 0
#define RookPSTMG_B8 0
#define RookPSTMG_C8 0
#define RookPSTMG_D8 0
#define RookPSTMG_E8 0
#define RookPSTMG_F8 0
#define RookPSTMG_G8 0
#define RookPSTMG_H8 0
#define RookPSTEG_A1 0
#define RookPSTEG_B1 0
#define RookPSTEG_C1 0
#define RookPSTEG_D1 0
#define RookPSTEG_E1 0
#define RookPSTEG_F1 0
#define RookPSTEG_G1 0
#define RookPSTEG_H1 0
#define RookPSTEG_A2 0
#define RookPSTEG_B2 0
#define RookPSTEG_C2 0
#define RookPSTEG_D2 0
#define RookPSTEG_E2 0
#define RookPSTEG_F2 0
#define RookPSTEG_G2 0
#define RookPSTEG_H2 0
#define RookPSTEG_A3 0
#define RookPSTEG_B3 0
#define RookPSTEG_C3 0
#define RookPSTEG_D3 0
#define RookPSTEG_E3 0
#define RookPSTEG_F3 0
#define RookPSTEG_G3 0
#define RookPSTEG_H3 0
#define RookPSTEG_A4 0
#define RookPSTEG_B4 0
#define RookPSTEG_C4 0
#define RookPSTEG_D4 0
#define RookPSTEG_E4 0
#define RookPSTEG_F4 0
#define RookPSTEG_G4 0
#define RookPSTEG_H4 0
#define RookPSTEG_A5 0
#define RookPSTEG_B5 0
#define RookPSTEG_C5 0
#define RookPSTEG_D5 0
#define RookPSTEG_E5 0
#define RookPSTEG_F5 0
#define RookPSTEG_G5 0
#define RookPSTEG_H5 0
#define RookPSTEG_A6 0
#define RookPSTEG_B6 0
#define RookPSTEG_C6 0
#define RookPSTEG_D6 0
#define RookPSTEG_E6 0
#define RookPSTEG_F6 0
#define RookPSTEG_G6 0
#define RookPSTEG_H6 0
#define RookPSTEG_A7 0
#define RookPSTEG_B7 0
#define RookPSTEG_C7 0
#define RookPSTEG_D7 0
#define RookPSTEG_E7 0
#define RookPSTEG_F7 0
#define RookPSTEG_G7 0
#define RookPSTEG_H7 0
#define RookPSTEG_A8 0
#define RookPSTEG_B8 0
#define RookPSTEG_C8 0
#define RookPSTEG_D8 0
#define RookPSTEG_E8 0
#define RookPSTEG_F8 0
#define RookPSTEG_G8 0
#define RookPSTEG_H8 0
#define QueenPSTMG_A1 0
#define QueenPSTMG_B1 0
#define QueenPSTMG_C1 0
#define QueenPSTMG_D1 0
#define QueenPSTMG_E1 0
#define QueenPSTMG_F1 0
#define QueenPSTMG_G1 0
#define QueenPSTMG_H1 0
#define QueenPSTMG_A2 0
#define QueenPSTMG_B2 0
#define QueenPSTMG_C2 0
#define QueenPSTMG_D2 0
#define QueenPSTMG_E2 0
#define QueenPSTMG_F2 0
#define QueenPSTMG_G2 0
#define QueenPSTMG_H2 0
#define QueenPSTMG_A3 0
#define QueenPSTMG_B3 0
#define QueenPSTMG_C3 0
#define QueenPSTMG_D3 0
#define QueenPSTMG_E3 0
#define QueenPSTMG_F3 0
#define QueenPSTMG_G3 0
#define QueenPSTMG_H3 0
#define QueenPSTMG_A4 0
#define QueenPSTMG_B4 0
#define QueenPSTMG_C4 0
#define QueenPSTMG_D4 0
#define QueenPSTMG_E4 0
#define QueenPSTMG_F4 0
#define QueenPSTMG_G4 0
#define QueenPSTMG_H4 0
#define QueenPSTMG_A5 0
#define QueenPSTMG_B5 0
#define QueenPSTMG_C5 0
#define QueenPSTMG_D5 0
#define QueenPSTMG_E5 0
#define QueenPSTMG_F5 0
#define QueenPSTMG_G5 0
#define QueenPSTMG_H5 0
#define QueenPSTMG_A6 0
#define QueenPSTMG_B6 0
#define QueenPSTMG_C6 0
#define QueenPSTMG_D6 0
#define QueenPSTMG_E6 0
#define QueenPSTMG_F6 0
#define QueenPSTMG_G6 0
#define QueenPSTMG_H6 0
#define QueenPSTMG_A7 0
#define QueenPSTMG_B7 0
#define QueenPSTMG_C7 0
#define QueenPSTMG_D7 0
#define QueenPSTMG_E7 0
#define QueenPSTMG_F7 0
#define QueenPSTMG_G7 0
#define QueenPSTMG_H7 0
#define QueenPSTMG_A8 0
#define QueenPSTMG_B8 0
#define QueenPSTMG_C8 0
#define QueenPSTMG_D8 0
#define QueenPSTMG_E8 0
#define QueenPSTMG_F8 0
#define QueenPSTMG_G8 0
#define QueenPSTMG_H8 0
#define QueenPSTEG_A1 0
#define QueenPSTEG_B1 0
#define QueenPSTEG_C1 0
#define QueenPSTEG_D1 0
#define QueenPSTEG_E1 0
#define QueenPSTEG_F1 0
#define QueenPSTEG_G1 0
#define QueenPSTEG_H1 0
#define QueenPSTEG_A2 0
#define QueenPSTEG_B2 0
#define QueenPSTEG_C2 0
#define QueenPSTEG_D2 0
#define QueenPSTEG_E2 0
#define QueenPSTEG_F2 0
#define QueenPSTEG_G2 0
#define QueenPSTEG_H2 0
#define QueenPSTEG_A3 0
#define QueenPSTEG_B3 0
#define QueenPSTEG_C3 0
#define QueenPSTEG_D3 0
#define QueenPSTEG_E3 0
#define QueenPSTEG_F3 0
#define QueenPSTEG_G3 0
#define QueenPSTEG_H3 0
#define QueenPSTEG_A4 0
#define QueenPSTEG_B4 0
#define QueenPSTEG_C4 0
#define QueenPSTEG_D4 0
#define QueenPSTEG_E4 0
#define QueenPSTEG_F4 0
#define QueenPSTEG_G4 0
#define QueenPSTEG_H4 0
#define QueenPSTEG_A5 0
#define QueenPSTEG_B5 0
#define QueenPSTEG_C5 0
#define QueenPSTEG_D5 0
#define QueenPSTEG_E5 0
#define QueenPSTEG_F5 0
#define QueenPSTEG_G5 0
#define QueenPSTEG_H5 0
#define QueenPSTEG_A6 0
#define QueenPSTEG_B6 0
#define QueenPSTEG_C6 0
#define QueenPSTEG_D6 0
#define QueenPSTEG_E6 0
#define QueenPSTEG_F6 0
#define QueenPSTEG_G6 0
#define QueenPSTEG_H6 0
#define QueenPSTEG_A7 0
#define QueenPSTEG_B7 0
#define QueenPSTEG_C7 0
#define QueenPSTEG_D7 0
#define QueenPSTEG_E7 0
#define QueenPSTEG_F7 0
#define QueenPSTEG_G7 0
#define QueenPSTEG_H7 0
#define QueenPSTEG_A8 0
#define QueenPSTEG_B8 0
#define QueenPSTEG_C8 0
#define QueenPSTEG_D8 0
#define QueenPSTEG_E8 0
#define QueenPSTEG_F8 0
#define QueenPSTEG_G8 0
#define QueenPSTEG_H8 0
#define KingPSTMG_A1 0
#define KingPSTMG_B1 0
#define KingPSTMG_C1 0
#define KingPSTMG_D1 0
#define KingPSTMG_E1 0
#define KingPSTMG_F1 0
#define KingPSTMG_G1 0
#define KingPSTMG_H1 0
#define KingPSTMG_A2 0
#define KingPSTMG_B2 0
#define KingPSTMG_C2 0
#define KingPSTMG_D2 0
#define KingPSTMG_E2 0
#define KingPSTMG_F2 0
#define KingPSTMG_G2 0
#define KingPSTMG_H2 0
#define KingPSTMG_A3 0
#define KingPSTMG_B3 0
#define KingPSTMG_C3 0
#define KingPSTMG_D3 0
#define KingPSTMG_E3 0
#define KingPSTMG_F3 0
#define KingPSTMG_G3 0
#define KingPSTMG_H3 0
#define KingPSTMG_A4 0
#define KingPSTMG_B4 0
#define KingPSTMG_C4 0
#define KingPSTMG_D4 0
#define KingPSTMG_E4 0
#define KingPSTMG_F4 0
#define KingPSTMG_G4 0
#define KingPSTMG_H4 0
#define KingPSTMG_A5 0
#define KingPSTMG_B5 0
#define KingPSTMG_C5 0
#define KingPSTMG_D5 0
#define KingPSTMG_E5 0
#define KingPSTMG_F5 0
#define KingPSTMG_G5 0
#define KingPSTMG_H5 0
#define KingPSTMG_A6 0
#define KingPSTMG_B6 0
#define KingPSTMG_C6 0
#define KingPSTMG_D6 0
#define KingPSTMG_E6 0
#define KingPSTMG_F6 0
#define KingPSTMG_G6 0
#define KingPSTMG_H6 0
#define KingPSTMG_A7 0
#define KingPSTMG_B7 0
#define KingPSTMG_C7 0
#define KingPSTMG_D7 0
#define KingPSTMG_E7 0
#define KingPSTMG_F7 0
#define KingPSTMG_G7 0
#define KingPSTMG_H7 0
#define KingPSTMG_A8 0
#define KingPSTMG_B8 0
#define KingPSTMG_C8 0
#define KingPSTMG_D8 0
#define KingPSTMG_E8 0
#define KingPSTMG_F8 0
#define KingPSTMG_G8 0
#define KingPSTMG_H8 0
#define KingPSTEG_A1 0
#define KingPSTEG_B1 0
#define KingPSTEG_C1 0
#define KingPSTEG_D1 0
#define KingPSTEG_E1 0
#define KingPSTEG_F1 0
#define KingPSTEG_G1 0
#define KingPSTEG_H1 0
#define KingPSTEG_A2 0
#define KingPSTEG_B2 0
#define KingPSTEG_C2 0
#define KingPSTEG_D2 0
#define KingPSTEG_E2 0
#define KingPSTEG_F2 0
#define KingPSTEG_G2 0
#define KingPSTEG_H2 0
#define KingPSTEG_A3 0
#define KingPSTEG_B3 0
#define KingPSTEG_C3 0
#define KingPSTEG_D3 0
#define KingPSTEG_E3 0
#define KingPSTEG_F3 0
#define KingPSTEG_G3 0
#define KingPSTEG_H3 0
#define KingPSTEG_A4 0
#define KingPSTEG_B4 0
#define KingPSTEG_C4 0
#define KingPSTEG_D4 0
#define KingPSTEG_E4 0
#define KingPSTEG_F4 0
#define KingPSTEG_G4 0
#define KingPSTEG_H4 0
#define KingPSTEG_A5 0
#define KingPSTEG_B5 0
#define KingPSTEG_C5 0
#define KingPSTEG_D5 0
#define KingPSTEG_E5 0
#define KingPSTEG_F5 0
#define KingPSTEG_G5 0
#define KingPSTEG_H5 0
#define KingPSTEG_A6 0
#define KingPSTEG_B6 0
#define KingPSTEG_C6 0
#define KingPSTEG_D6 0
#define KingPSTEG_E6 0
#define KingPSTEG_F6 0
#define KingPSTEG_G6 0
#define KingPSTEG_H6 0
#define KingPSTEG_A7 0
#define KingPSTEG_B7 0
#define KingPSTEG_C7 0
#define KingPSTEG_D7 0
#define KingPSTEG_E7 0
#define KingPSTEG_F7 0
#define KingPSTEG_G7 0
#define KingPSTEG_H7 0
#define KingPSTEG_A8 0
#define KingPSTEG_B8 0
#define KingPSTEG_C8 0
#define KingPSTEG_D8 0
#define KingPSTEG_E8 0
#define KingPSTEG_F8 0
#define KingPSTEG_G8 0
#define KingPSTEG_H8 0
