name: macos

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: git submodule retrieval
      run: |
        git submodule init
        git submodule update
    - name: cmake
      run: cmake -B app/src/linux-windows/build -S app/src/linux-windows
    - name: make
      run: make -C app/src/linux-windows/build Dog
    - name: store artifact in GitHub
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: app/src/linux-windows/build/Dog
        retention-days: 2
